### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by tomjimlondon** [AmirhosseinChami/Telegram-ChatGPT-bot#1]
Hello there,

I just try your code, but unfortunately I have an error.

AttributeError:  module 'telethon.tl.custom.button' has no attribute 'inline'

Any suggestion on how to solve it?

**Comment by AmirhosseinChami** [comment]
Hello dear tom,
I fixed it . The problem was the import of the package in line 2 and use of
it in line 11 !
I committed the correct code on the repository again.
Clone the repository and use it. I would be so happy to help you if there
is any problem.
Thank you for contacting me.

‫‪Tom Jim‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۲۹ مارس ۲۰۲۳
ساعت ۱۲:۴۵ نوشت:‬

**Comment by tomjimlondon** [comment]
Thank you so much for this
